### Вычислить индекс массы тела (POST)
POST http://localhost:8080/api/calculator
Content-Type: application/json

{
  "weight":83,
  "height": 1.65}


### Вычислить индекс массы тела (POST)
POST http://localhost:8080/api/calculator
Content-Type: application/json

{
  "weight":61,
  "height": 1.60}

### Вычислить индекс массы тела (POST)
POST http://localhost:8080/api/calculator
Content-Type: application/json

{
  "weight":56,
  "height": 1.55}

### Проверяем ошибку валидации
POST http://localhost:8080/api/calculator
Content-Type: application/json

{
  "weight":-98,
  "height": 251}

### Проверяем неправильное название категории
POST http://localhost:8080/api/calculator
Content-Type: application/json

{
  "weight000":-98,
  "height": 251}



### GET /api/getAll для получения всех результатов
GET http://localhost:8080/api/getAll
Accept: application/json



### GET /api/ поиск по id
GET http://localhost:8080/api/2
Accept: application/json

### DELETE /api/ удаление по id
DELETE http://localhost:8080/api/2
Accept: application/json


### DELETE /api/ удаление всех записей
DELETE http://localhost:8080/api/deleteAll
Accept: application/json


### GET /api/ получение статистики
GET http://localhost:8080/api/statistics
Accept: application/json


### Обновить вес
PUT http://localhost:8080/api/43
Content-Type: application/json

{
  "updatedWeight":64
  }