### Вычислить индекс массы тела (POST)
POST http://localhost:8080/api/calculator?userId=8
Content-Type: application/json

{
  "weight":79,
  "height": 1.80}


### Вычислить индекс массы тела (POST)
POST http://localhost:8080/api/calculator?userId=9
Content-Type: application/json

{
  "weight":64,
  "height": 1.60}

### Вычислить индекс массы тела (POST)
POST http://localhost:8080/api/calculator
Content-Type: application/json

{
  "weight":56,
  "height": 1.55}

### Проверяем ошибку валидации
POST http://localhost:8080/api/calculator
Content-Type: application/json

{
  "weight":-98,
  "height": 251}

### Проверяем неправильное название категории
POST http://localhost:8080/api/calculator
Content-Type: application/json

{
  "weight000":-98,
  "height": 251}



### GET /api/getAll для получения всех результатов
GET http://localhost:8080/api/getAll
Accept: application/json



### GET /api/ поиск по id
GET http://localhost:8080/api/2
Accept: application/json

### DELETE /api/ удаление по id
DELETE http://localhost:8080/api/2
Accept: application/json


### DELETE /api/ удаление всех записей
DELETE http://localhost:8080/api/deleteAll
Accept: application/json


### GET /api/ получение статистики
GET http://localhost:8080/api/statistics
Accept: application/json


### Обновить вес
PUT http://localhost:8080/api/43
Content-Type: application/json

{
  "updatedWeight":64
  }


### GET /api/ фильтрация по категории, %20 - то кодировка пробела
GET http://localhost:8080/api/filter?newCategory=нормальный%20вес
Accept: application/


### GET /api/ фильтрация по дате
GET http://localhost:8080/api/filter_for_date?dateForSearching=2026-03-19
Accept: application/json

### GET /api/ фильтрация по временному периоду
GET http://localhost:8080/api/filter_by_date_period?startDate=2026-03-18&endDate=2026-03-19
Accept: application/json


### создаем нового пользователя (POST)
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Anna",
  "email": "ovcharnikova@yandex.ru"}

### создаем нового пользователя (POST)
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Alena",
  "email": "Volkova@yandex.ru"}

### создаем нового пользователя (POST)
POST http://localhost:8080/api/users
Content-Type: application/json

  {
    "name": "Afina",
    "email": "krasivaya@yandex.ru"}

### GET /api/
GET http://localhost:8080/api/users/6/results
Accept: application/json
