spring.application.name=BodyWeightCalculator
## H2 Database
#spring.datasource.url=jdbc:h2:mem:bmidb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## H2 Console (для просмотра базы в браузере)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.web=DEBUG

#для использования локальной базы PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/results
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Producer (отправка событий)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer (приём событий, если слушать внутри этого же приложения)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=bmi-group
spring.kafka.consumer.properties.spring.json.trusted.packages=*
